#!/bin/bash

IPTABLES_RESTORE="/sbin/iptables-restore"
IPTABLES_FILE="/etc/interspire/puppet-firewall.conf"

if [ -x $IPTABLES_RESTORE ]; then
    if [ -f $IPTABLES_FILE ]; then
        $IPTABLES_RESTORE < $IPTABLES_FILE
    fi
fi

